# .github/workflows/deploy.yml
name: CI/CD Flask Docker

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build Docker image
        run: docker build -t flask-app .

      - name: Save Docker image
        run: docker save flask-app -o flask-app.tar

      - name: Copy image to EC2
        uses: appleboy/scp-action@v0.1.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          source: "flask-app.tar"
          target: "/home/ubuntu/flask-app.tar"

      - name: Load Docker image on EC2 & run
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            docker load -i flask-app.tar
            docker stop flask-app || true
            docker rm flask-app || true
            docker run -d -p 5000:5000 --name flask-app flask-app