- name: Deploy Flask App to EC2
  uses: appleboy/ssh-action@v0.1.6
  with:
    host: ${{ secrets.EC2_HOST }}      # EC2 public IP
    username: ubuntu
    key: ${{ secrets.EC2_SSH_KEY }}    # Your SSH key secret
    port: 22
    script: |
      cd ~/flask-devops-app
      docker-compose pull
      docker-compose up -d --build
